GitHub Action to automatically build master branch on commit
TeslaGov/ngx-http-auth-jwt-module pull request #108
Opened 2023-08-21 12:35 UTC by KnownEntity

Wrote this up mostly to see if I could. This was mentioned by https://github.com/TeslaGov/ngx-http-auth-jwt-module/issues/73 and I tend to agree.

This workflow can be triggered manually or by commit to the master branch and will automatically:
1. Build against multiple Nginx and libjwt versions.
2. Upload the results as a Pre-release Development build.

You can see the [action](https://github.com/KnownEntity/ngx-http-auth-jwt-module/actions/runs/5925724845) working on my fork and the release [here](https://github.com/KnownEntity/ngx-http-auth-jwt-module/releases/tag/dev-build).
The Nginx versions to build against can be easily changed by modifying the `nginx-version` list.
Sadly, it doesn't perform build tests in its current state. I'm sure that can be added but I was not inclined to work on that at the moment.
The rationale behind using multiple versions of libjwt came after I discovered the hard way that the current binary release won't link against any version of libjwt above 1.12.0 and EPEL currently has 1.12.1.

Open to feedback and of course, change anything you want.
Thanks for making this project!

2023-08-23 16:49 UTC, JoshMcCullough requested changes
Thank you for this! A couple changes...

2023-08-23 16:49 UTC, JoshMcCullough commented on .github/workflows/ci.yml
> +        libjwt-version: ['v1.12.0', 'v1.14.0', 'v1.15.3']
```suggestion
        libjwt-version: ['1.12.0', '1.14.0', '1.15.3']
```

2023-08-23 16:49 UTC, JoshMcCullough commented on .github/workflows/ci.yml
> +        ref: '${{matrix.libjwt-version}}'
```suggestion
        ref: 'v${{matrix.libjwt-version}}'
```

2023-08-23 16:49 UTC, JoshMcCullough commented on .github/workflows/ci.yml
> +            - Reference commit: ${{ github.sha }}
```suggestion
            > [!WARNING]
            > This is an automatically generated pre-release version of the module, which includes the latest master branch changes.
            > Please report any bugs you find to the issue tracker.

            - Build Date: `${{ steps.vars.outputs.date_now }}`
            - Commit: ${{ github.sha }}
```

2023-08-23 16:49 UTC, JoshMcCullough commented on .github/workflows/ci.yml
> +          name: Development build
```suggestion
          name: 'Development build: ${{ github.ref_name }}@${{ github.sha }}'
```

2023-08-23 23:08 UTC, JoshMcCullough approved these changes

2023-08-23 23:08 UTC, merged

2023-08-23 23:12 UTC, JoshMcCullough commented
@KnownEntity that worked great -- thanks again!

2023-08-24 12:40 UTC, KnownEntity commented
Glad I could help.