add support for ES algorithms
TeslaGov/ngx-http-auth-jwt-module pull request #118
Opened 2023-12-05 07:43 UTC by swaeberle

See #117

2023-12-05 14:50 UTC, JoshMcCullough requested changes
Thanks for this. Can you please add tests matching those for RS*?

2023-12-05 14:55 UTC, swaeberle commented
> Thanks for this. Can you please add tests matching those for RS*?

I'll have a look on this, too!

2023-12-06 10:10 UTC, swaeberle commented
Unfortunately, I was not able to run the tests locally due to missing authentication with docker.io.
```
Building test runner using port 8000...
[+] Building 1.0s (3/3) FINISHED                                                                                                                                                                                                      docker:default
 => [nginx internal] load build definition from Dockerfile-test-nginx                                                                                                                                                                           0.0s
 => => transferring dockerfile: 601B                                                                                                                                                                                                            0.0s
 => [nginx internal] load .dockerignore                                                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => ERROR [nginx internal] load metadata for docker.io/teslagov/jwt-nginx:1.24.0                                                                                                                                                                0.9s
------
 > [nginx internal] load metadata for docker.io/teslagov/jwt-nginx:1.24.0:
------
failed to solve: teslagov/jwt-nginx:1.24.0: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

2024-01-22 14:25 UTC, JoshMcCullough requested changes
Sorry for the delay. It's close -- make sure all instances of ES 512 are `512` and not `521`.

2024-01-22 14:25 UTC, JoshMcCullough commented on test/Dockerfile-test-nginx
> +COPY /etc/nginx/ec_key_521-pub.pem /etc/nginx/ec-521-key.conf
`521` should be `512`.

2024-01-22 14:25 UTC, JoshMcCullough commented on test/ec_key_521.pem
Should be `512`.

2024-01-22 14:25 UTC, JoshMcCullough commented on test/etc/nginx/ec_key_521-pub.pem
Should be `512`.

2024-01-22 14:44 UTC, swaeberle commented
> Sorry for the delay. It's close -- make sure all instances of ES 512 are `512` and not `521`.

In fact the naming is no mixup but intended.

I used the elliptic curve `NIST P-521` to create the keys with `-521` suffix. Only later the key is used in combination with `SHA-512` to form JWT algorithm `ES512` (as defined by [RFC 7518 section 3.4](https://www.rfc-editor.org/rfc/rfc7518#section-3.4)).

So the number originates from the named elliptic curve, not the hash function.

Though for the other JWT algorithms, named curve and hash function are equivalent.

2024-03-17 01:55 UTC, beeing commented
Hi, any resolution on this? I'm interested to use it with this too. Thanks in advance!

2024-03-18 14:27 UTC, swaeberle commented
@JoshMcCullough Are you fine with keeping the test keys file names or do you insist in renaming them?

2024-03-18 16:25 UTC, JoshMcCullough commented
> @JoshMcCullough Are you fine with keeping the test keys' file names or do you insist in renaming them?

Thank you for clarifying -- my mistake.

2024-03-18 16:32 UTC, merged

2024-03-18 16:36 UTC, JoshMcCullough commented
v2.1.0: https://github.com/TeslaGov/ngx-http-auth-jwt-module/releases/tag/2.1.0